### ISSUE TITLE
provide ability to efficiently get a single file from a tarball without a full download

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#373]
ATM we extract entire tarball so we could "get" possibly just few necessary files.
But it might be worth, while creating our archive:// urls to incorporate seek position for that file within the tarball (so as if it was not gzipped we could just jump to that point right away to extract the file), and then store complimentary index of gzip  seek points (e.g. spaced at each 10MB or so, each one would need 32K of initialization data) so at some minor cost we could later efficiently jump to the location where file starts within tar and extract it without extracting entire archive.  Related project: https://github.com/pauldmccarthy/indexed_gzip/ which we might leverage/contribute to without needing to rewrite everything from scratch
@joeyh we did talk about smth like that at some point, didn't we?

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> @joeyh we did talk about smth like that at some point, didn't we?

Maybe.. I probably suggested using SETSTATE to have the special remote
store the data.

-- 
see shy jo

**Comment by mih** [comment]
How relevant is this issue almost four years later? Can we close this? With 7zip indexed archives are available that support random access.

**Comment by yarikoptic** [comment]
Well, the issue is still not resolved -- we cannot fetch selected file(s) from within tarballs (or 7zip indexed archives for that matter) without `get`'ing those archives fully first.

BTW, how much of 7zip "header" you would need to pre-fetch first to then access a specific file at some offset down the road?  Is index of files just a list of there is some hierarchical structure so drilling down to specific file would be just a few random accesses in the header and then jump to the target location?  I now dumped some kind of a the idea for a prototype to provide "seamless" access to portions of the files under git-annex in https://github.com/datalad/datalad/issues/4003 .

**Comment by mih** [comment]
I have edited the title to clarify the intent of this issue.

**Comment by bpoldrack** [comment]
Almost three years later, do you still think this is relevant in the core package, @yarikoptic or (to-be)addressed by datalad-fuse?

**Comment by yarikoptic** [comment]
well, it is probably something to be implemented within `datalad-archive` special remote which is part of this core package, so issue is still pertinent but since nobody worked it out -- let's let it RiP for now with appropriate labels attached.
