### ISSUE TITLE
CI: travis debug run overfills the log, fails travis run 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5244]
atn @mih: after merge of #5163 (I thought  master started to fail consistently (see https://travis-ci.com/github/datalad/datalad/builds) upon debug run due to all the now dumped git-annex debug logs.  I thought it was discussed and fixed up for, but apparently not. FWIW: The last commits in that PR seems to not have any travis run reported back at all.

**Comment by kyleam** [comment]
This is addressed in gh-5229 [1].   If that's held up with crawler/protocol discussion, I believe we should still be able to cherry pick f7cb4908ca (BF: Prevent leakage of annex debug output at high log levels) as well as everything after it.

  [1] last travis build there: https://travis-ci.com/github/datalad/datalad/builds/208131671

> FWIW: The last commits in that PR seems to not have any travis run reported back at all.

The last two commits were docstring/comment tweaks and marked with `[ci skip]`.

**Comment by yarikoptic** [comment]
great, thank you @kyleam !
I am still not sure why something was merged into master with a break to CI.

**Comment by kyleam** [comment]
Fixed by gh-5247.
