### ISSUE TITLE
datalad install should group files for a single 'annex get' invocation

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#553]
ATM, it takes a while to run e.g. 'datalad install *.dcm' whenever those files come e.g. from an archive which is already extracted etc... primarily it is because install calls 'annex get' on each file separately, which in turn starts a separate git-annex-remote-datalad-archives... that consumes time for no good reason.  The same applies to uninstall.

See e.g. below 10x difference while 'installing' or 'dropping' 10 files.

```shell
$> DATALAD_LOGLEVEL=WARN /usr/bin/time datalad install 032*.dcm
10 installed items are available at
/tmp/collection_2014_subdicoms/DICOMS/OvalsTI001_raw_DICOM/run1/0320.dcm
...
4.71user 1.02system 0:06.49elapsed 88%CPU (0avgtext+0avgdata 41232maxresident)k

hopa:/tmp/collection_2014_subdicoms/DICOMS/OvalsTI001_raw_DICOM/run1
$> DATALAD_LOGLEVEL=WARN /usr/bin/time datalad uninstall 032*.dcm
4.76user 1.17system 0:06.76elapsed 87%CPU (0avgtext+0avgdata 41156maxresident)k

hopa:/tmp/collection_2014_subdicoms/DICOMS/OvalsTI001_raw_DICOM/run1
$> DATALAD_LOGLEVEL=WARN /usr/bin/time git annex get 032*.dcm    
get 0320.dcm (from datalad-archives...) 
...
(recording state in git...)
0.44user 0.07system 0:00.57elapsed 89%CPU (0avgtext+0avgdata 41492maxresident)k
16inputs+0outputs (0major+28794minor)pagefaults 0swaps
```
not to say that one file at a time creates a commit to git-annex for each one of those gets I think... we should try to minimize amount of commits one way or another

**Comment by hanke** [comment]
Sounds right. No immediate idea for an implementation though. Needs some thought.

**Comment by yarikoptic** [comment]
could be as simple as going through the list of provided files, checking which are present and under git/annex control, groupping them and processing together and then going to others

eventually we would need similar, but fuller analysis anyways, so we could decide which stuff to get from where (e.g. which archive key to fetch before asking annex to get those files coming from the archive(s))

**Comment by hanke** [comment]
... after having figured out which (possibly yet to be installed) subdataset they belong to ...

**Comment by yarikoptic** [comment]
subdatasets is a 2nd beast -- they would need their own 'annex get' calls anyways

so i would have done a pass first to figure out what files correspond to this specific annex, and "the rest".  Do a single call to 'annex get files' and then proceed with treating all others (submodules etc)

**Comment by hanke** [comment]
Which translates to a rewrite of `install`. That is OK, but non-trivial, hence me initial comment.

**Comment by yarikoptic** [comment]
Another quick and dirty help could be from batching 'annex get', so filed a TODO issue for annex: http://git-annex.branchable.com/todo/get_--batch/

**Comment by yarikoptic** [comment]
We keep running into this slowness issue during demos... kinda embarrassing.  @joeyh - any chance to get 'get --batch' soon?

**Comment by hanke** [comment]
FTR: Iteration over files takes about 120ms on my machine (with SSD), for a file that is already present.

**Comment by bpoldrack** [comment]
This is actually a matter of `get`, not of `install` and is addressed by new implementation of `get` in #613, which groups all paths for calls of `annex-get` per (sub-)dataset.

**Comment by yarikoptic** [comment]
It might be a matter of `get` indeed, but as far as I see it -- `install` in master still does the old drill and wasn't fixed or RFed anyhow (e.g. by groupping and passing to get  pointers to files/directories within current dataset; or by stripping 'get' functionality altogether, which we might discuss (against) later anyways).  So I would prefer issue to be open until resolved one way or another

**Comment by mih** [comment]
FYI: I created the 'fix-implemented' issue tag some time ago in order to
indicate r
that a fix is somewhere without having to close an issue.
