### ISSUE TITLE
`save --jobs` runs too many processes

### ISSUE THREAD

**Issue by MartinGrignard** [datalad/datalad#6344]
### What is the problem?

I'm using datalad for a research project which involves a lot of files (several tens of thousands) grouped in sub-datasets. Since the pipelines are very resource intensive and easily parallelized, I run everything on our local cluster.

Unfortunately, when I use `datalad save -J 1`, the number of instances of both git and git-annex still go crazy and the administrator of the cluster asked me to sort this out.

I tried adding this to my `.gitconfig`:
```
[datalad "runtime"]
	max-annex-jobs = 1
	max-jobs = 1
```

Do you have any idea on how to solve this? Is it the expected behavior?
Thanks,
Martin

### What steps will reproduce the problem?

I don't have an easy to reproduce example, but I basically try to save a lot of annex files.

### Datalad information

The version currently available on the cluster is `datalad 0.14.1`.

Here is the result of `datalad wtf`:
<details><summary>Output</summary>

## datalad 
  - full_version: 0.14.1
  - version: 0.14.1
## dependencies 
  - annexremote: 1.5.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 17.03
  - cmd:annex: 8.20210311-g24c576bfa
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.31.0
  - cmd:system-git: 2.31.0
  - cmd:system-ssh: 8.0p1
  - humanize: 3.3.0
  - iso8601: 0.1.14
  - keyring: 23.0.1
  - keyrings.alt: 4.0.2
  - msgpack: 1.0.2
  - requests: 2.25.1
  - wrapt: 1.12.1
## environment 
  - LANG: fr_BE.UTF-8
  - PATH: /home/ulg/crc/mgrgnrd/P2020-shamo/modules/modules/datalad/0.14.1/bin:/home/ulg/crc/mgrgnrd/P2020-shamo/modules/modules/git-annex/8.20210311:/home/ulg/crc/mgrgnrd/P2020-shamo/modules/modules/p7zip/17.03:/opt/cecisw/arch/easybuild/2019b/software/Python/3.7.4-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/XZ/5.2.4-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/SQLite/3.29.0-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/Tcl/8.6.9-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/ncurses/6.1-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/bzip2/1.0.8-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/binutils/2.32-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/GCCcore/8.3.0/bin:/home/ulg/crc/mgrgnrd/P2020-shamo/modules/modules/nextflow/21.04.3:/opt/cecisw/noarch/easybuild/2018.01/software/Java/11.0.2:/opt/cecisw/noarch/easybuild/2018.01/software/Java/11.0.2/bin:/home/ulg/crc/mgrgnrd/.local/bin:/home/ulg/crc/mgrgnrd/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
  - PYTHONPATH: /opt/cecisw/arch/easybuild/2019b/software/Python/3.7.4-GCCcore-8.3.0/easybuild/python
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20210311-g24c576bfa
## location 
  - path: /home/users/m/g/mgrgnrd
  - type: directory
## metadata_extractors 
  - annex (datalad 0.14.1): 
    - distribution: datalad 0.14.1
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.14.1): 
    - distribution: datalad 0.14.1
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite (datalad 0.14.1): 
    - distribution: datalad 0.14.1
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.14.1): 
    - distribution: datalad 0.14.1
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.14.1): 
    - distribution: datalad 0.14.1
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.14.1): 
    - distribution: datalad 0.14.1
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage (datalad 0.14.1): 
    - distribution: datalad 0.14.1
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.14.1): 
    - distribution: datalad 0.14.1
    - load_error: No module named 'PIL' [image.py:<module>:16]
    - module: datalad.metadata.extractors.image
  - xmp (datalad 0.14.1): 
    - distribution: datalad 0.14.1
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.7.4
## system 
  - distribution: CentOS Linux/8.2.2004/Core
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 277
  - name: Linux
  - release: 4.18.0-193.6.3.el8_2.x86_64
  - type: posix
  - version: #1 SMP Wed Jun 10 11:09:32 UTC 2020

</details>

### Have you had any success using DataLad before?

I've used the exact same command many times before and did never check the processes. In the end, it works, it's just that I cannot limit the number of sub-processes.

**Comment by yarikoptic** [comment]
> `cmd:annex: 8.20210311-g24c576bfa`

would you be able to try out with most recent release of git-annex?  I remember that we had some "run away" processes issues which were resolved in some not so distant past. (should be listed somewhere among "done" on https://git-annex.branchable.com/projects/datalad/ I think)

**Comment by yarikoptic** [comment]
oh 
> datalad 0.14.1

and definitely newer datalad - we had lots of related fixes since then.  you can get your own conda environment with recent(ish) git annex and datalad on HPC.  datalad-installer could be of help as well (available on pypi) .

**Comment by MartinGrignard** [comment]
I installed `datalad 0.15.4` and `git-annex 2021118` (See the result of `datalad wtf` down bellow) but the problem remains the same.

<details><summary>Output</summary>

## datalad 
  - version: 0.15.4
## dependencies 
  - annexremote: 1.5.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 17.03
  - cmd:annex: 8.20211118-g23ee48898
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.34.0
  - cmd:system-git: 2.34.0
  - cmd:system-ssh: 8.0p1
  - humanize: 3.13.1
  - iso8601: 1.0.2
  - keyring: 23.4.1
  - keyrings.alt: 4.1.0
  - msgpack: 1.0.3
  - requests: 2.27.1
  - wrapt: 1.13.3
## environment 
  - LANG: en_GB.UTF-8
  - LC_ADDRESS: fr_BE.UTF-8
  - LC_IDENTIFICATION: fr_BE.UTF-8
  - LC_MEASUREMENT: fr_BE.UTF-8
  - LC_MONETARY: fr_BE.UTF-8
  - LC_NAME: fr_BE.UTF-8
  - LC_NUMERIC: fr_BE.UTF-8
  - LC_PAPER: fr_BE.UTF-8
  - LC_TELEPHONE: fr_BE.UTF-8
  - LC_TIME: fr_BE.UTF-8
  - PATH: /home/ulg/crc/mgrgnrd/P2020-shamo/modules/modules/datalad/0.15.4/bin:/home/ulg/crc/mgrgnrd/P2020-shamo/modules/modules/git-annex/8.20211118:/home/ulg/crc/mgrgnrd/P2020-shamo/modules/modules/p7zip/17.03:/opt/cecisw/arch/easybuild/2019b/software/Python/3.7.4-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/XZ/5.2.4-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/SQLite/3.29.0-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/Tcl/8.6.9-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/ncurses/6.1-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/bzip2/1.0.8-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/binutils/2.32-GCCcore-8.3.0/bin:/opt/cecisw/arch/easybuild/2019b/software/GCCcore/8.3.0/bin:/home/ulg/crc/mgrgnrd/P2020-shamo/modules/modules/nextflow/21.04.3:/opt/cecisw/noarch/easybuild/2018.01/software/Java/11.0.2:/opt/cecisw/noarch/easybuild/2018.01/software/Java/11.0.2/bin:/home/ulg/crc/mgrgnrd/.local/bin:/home/ulg/crc/mgrgnrd/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
  - PYTHONPATH: /opt/cecisw/arch/easybuild/2019b/software/Python/3.7.4-GCCcore-8.3.0/easybuild/python
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20211118-g23ee48898
## location 
  - path: /home/users/m/g/mgrgnrd
  - type: directory
## metadata_extractors 
  - annex (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: ModuleNotFoundError(No module named 'mutagen')
    - module: datalad.metadata.extractors.audio
  - datacite (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: ModuleNotFoundError(No module named 'exifread')
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: ModuleNotFoundError(No module named 'PIL')
    - module: datalad.metadata.extractors.image
  - xmp (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## metadata_indexers 
## python 
  - implementation: CPython
  - version: 3.7.4
## system 
  - distribution: CentOS Linux/8.2.2004/Core
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 277
  - name: Linux
  - release: 4.18.0-193.6.3.el8_2.x86_64
  - type: posix
  - version: #1 SMP Wed Jun 10 11:09:32 UTC 2020

</details>

**Comment by adswa** [comment]
related: #5955

**Comment by yarikoptic** [comment]
We haven't heard back on this in a while, and there were zombie preventive fixes in git annex around those times, see  https://git-annex.branchable.com/forum/git-annex_causing_zombie_git_processes_to_build_up/#comment-08ec237f13019557e3162709d03ce40c so I will consider that issue was addressed, or is a duplicate of #5955 . If it isn't feel welcome to reopen and let's look at it again
