### ISSUE TITLE
webface: [object Object]  for top level or empty datasets (ds000053)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#718]

**Comment by debanjum** [comment]
This was an artifact of a failed publish rather than a bug

**Comment by debanjum** [comment]
bf94ff2067dc6b647bc947728fa4de737f314cfc should fix it

**Comment by yarikoptic** [comment]
For ds 17 in openfmri
http://datasets.datalad.org/webtest/?dir=/openfmri
Still not good or not yet refreshed?

**Comment by debanjum** [comment]
Just noticed that, no the ds 17 was put separately as it didn't get installed on the first run.
I just ran datalad ls -a on the datasets after my fix but it seems like ds 17 doesn't get recognized as a dataset anymore for some reason.
