### ISSUE TITLE
Issue with symlinked top level repository directory

### ISSUE THREAD

**Issue by TheChymera** [datalad/datalad#7438]
### What is the problem?

Datalad seems to get confused if the top level of the repository is navigated to via a symlink.

### What steps will reproduce the problem?

```console
[typhon]~/.local/share/datalad/vStr_phase_stim ❱ datalad get .
FileNotInRepositoryError:  [Path outside repository: /data/studies/manish/vStr_phase_stim]
[Errno None] : Path outside repository: /data/studies/manish/vStr_phase_stim: '/home/chymera/.local/share/datalad/vStr_phase_stim'
[typhon]~/.local/share/datalad/vStr_phase_stim ❱ pwd
/home/chymera/.local/share/datalad/vStr_phase_stim
[typhon]~/.local/share/datalad/vStr_phase_stim ❱ cd /data/studies/manish/vStr_phase_stim/
[typhon]/data/studies/manish/vStr_phase_stim ❱ datalad get .
[typhon]/data/studies/manish/vStr_phase_stim ❱
```

### DataLad information

<details>
<summary>WTF etc</summary> 

```
[typhon]~ ❱ datalad --version
datalad 0.18.3
[typhon]~ ❱ datalad wtf
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - SecretService Keyring
      - libsecret Keyring
      - EncryptedKeyring with [PBKDF2] AES256.CFB v.1.0 at /home/chymera/.local/share/python_keyring/crypted_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at /home/chymera/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/chymera/.config/python_keyring/keyringrc.cfg
    - data_root: /home/chymera/.local/share/python_keyring
## datalad
  - version: 0.18.3
## dependencies
  - annexremote: 1.6.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 10.20230126
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.39.2
  - cmd:ssh: 9.2p1
  - cmd:system-git: 2.39.2
  - cmd:system-ssh: 9.2p1
  - humanize: 0.0.0
  - iso8601: 1.0.2
  - keyring: 23.9.3
  - keyrings.alt: 4.2.0
  - msgpack: 1.0.3
  - requests: 2.28.1
## environment
  - LANG: en_US.UTF-8
  - PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/cuda/bin
## extensions
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.22.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.29
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-9.0.2
    - http-client-0.7.13.1
    - persistent-sqlite-2.13.1.0
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.2.1
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
    - 9
    - 10
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20230126
## location
  - path: /home/chymera
  - type: directory
## python
  - implementation: CPython
  - version: 3.11.2
## system
  - distribution: debian/12/bookworm
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem:
    - CWD:
      - max_pathlength: 4096
      - mount_opts: rw,noatime,compress=lzo,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/home
      - path: /home/chymera
      - type: btrfs
    - HOME:
      - max_pathlength: 4096
      - mount_opts: rw,noatime,compress=lzo,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/home
      - path: /home/chymera
      - type: btrfs
    - TMP:
      - max_pathlength: 4096
      - mount_opts: rw,relatime
      - path: /tmp
      - type: ext4
  - max_path_length: 269
  - name: Linux
  - release: 6.1.0-3-amd64
  - type: posix
  - version: #1 SMP PREEMPT_DYNAMIC Debian 6.1.8-1 (2023-01-29)
  ```

</details>

### Have you had any success using DataLad before?

yes

**Comment by christian-monch** [comment]
@yarikoptic: the exception is raised in `_normalize_path`. Do we want to support symlinks, or do we document that symlinked locations are not supported, or do you see another way forward here?

**Comment by yarikoptic** [comment]
insofar we thought that we supported them. It is a bug and should be fixed -- it would be really not good to claim that we cannot work in sumlinked folders whenever git and git-annex have no problem

**Comment by TheChymera** [comment]
any updates on this? I'm still encountering this issue with `=datalad-0.19.6`:

```console
[deco]~/.local/share/datalad/mvmnda ❱ datalad get .
FileNotInRepositoryError:  [Path outside repository: /run/media/chymera/data2/mvmdna]
[Errno None] : Path outside repository: /run/media/chymera/data2/mvmdna: '/home/chymera/.local/share/datalad/mvmnda'
[deco]~/.local/share/datalad/mvmnda ❱ datalad --version
datalad 0.19.6
[deco]~/.local/share/datalad/mvmnda ❱ cd ..
[deco]~/.local/share/datalad ❱ ls -lah
total 8.0K
drwxr-xr-x  2 chymera chymera 4.0K Feb 12 07:56 .
drwxr-xr-x 30 chymera chymera 4.0K Feb 12 07:56 ..
lrwxrwxrwx  1 chymera chymera   32 Feb 12 07:56 mvmnda -> /run/media/chymera/data2/mvmdna/
lrwxrwxrwx  1 chymera chymera   48 May 27  2023 vStr_phase_stim -> /run/media/chymera/data2/datalad/vStr_phase_stim
```

**Comment by yarikoptic** [comment]
interestingly - for me the bug manifests differently: it just doesn't do anything:

```
❯ pwd
/home/yoh/proj/datalad/trash/datasets.datalad.org-symlinked
❯ ls -ld $PWD
lrwxrwxrwx 1 yoh yoh 20 Feb 12 11:24 /home/yoh/proj/datalad/trash/datasets.datalad.org-symlinked -> datasets.datalad.org/
❯ datalad get .
❯ echo $?
0
❯ datalad -f json_pp get .
{
  "action": "get",
  "message": [
    "nothing to get from %s",
    "/home/yoh/proj/datalad/trash/datasets.datalad.org-symlinked"
  ],
  "path": "/home/yoh/proj/datalad/trash/datasets.datalad.org-symlinked",
  "refds": "/home/yoh/proj/datalad/trash",
  "status": "notneeded",
  "type": "directory"
}
❯ datalad --version
datalad 0.19.6
```

wherever there is stuff to get 

```shell
❯ git annex find --not --in here | head
.datalad/metadata/objects/0e/cn-2e262d6ab40f1f0fa399e80866f732.xz
.datalad/metadata/objects/0e/ds-2df3eb99146fbd743f6599f7c6ef64
.datalad/metadata/objects/0e/ds-2e262d6ab40f1f0fa399e80866f732
.datalad/metadata/objects/0f/cn-3c0d085acbb8ea3af430f826828b69.xz
...
```
and it does get it when run in original directory:
```shell
❯ pwd
/home/yoh/proj/datalad/trash/datasets.datalad.org
❯ datalad get .
Total:  10%|█████████▎                                                                                      | 7.56M/78.0M [00:00<00:03, 23.4M Bytes/s]ERROR:                                                                                                                                                
Interrupted by user while doing magic: KeyboardInterrupt()
Total:  16%|███████████████▍                                                                                | 12.5M/78.0M [00:00<00:03, 19.3M Bytes/s]
```

and in my case it is due to an interesting execution, where instead of (how it runs in non-symlinked):

```shell
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', '-c', 'core.quotepath=false', '-c', 'annex.merge-annex-branches=false', 'annex', 'find', '--not', '--in', '.', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true', '--', '.'] with status 0 
```

we get 

```shell
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', '-c', 'core.quotepath=false', '-c', 'annex.merge-annex-branches=false', 'annex', 'find', '--not', '--in', '.', '--json', '--json-error-messages', '-c', 'annex.dotfiles=true', '--', 'datasets.datalad.org-symlinked'] with status 1 
[DEBUG  ] No files found needing fetching.
```
so a failed `find` on provided basename of the current path... To get original reported fail I symlink somewhere completely different -- into `/tmp` and then reproduce:

```shell
❯ pwd
/tmp/datasets.datalad.org
❯ ls -ld $PWD
lrwxrwxrwx 1 yoh yoh 49 Feb 12 11:32 /tmp/datasets.datalad.org -> /home/yoh/proj/datalad/trash/datasets.datalad.org/
❯ datalad -l debug get .
...
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', '-c', 'core.quotepath=false', 'config', '-z', '-l', '--file', '.gitmodules'] (protocol_class=GeneratorStdOutErrCapture) (cwd=/home/yoh/proj/datalad/trash/datasets.datalad.org) 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', '-c', 'core.quotepath=false', 'ls-files', '--stage', '-z', '--', 'abide', 'abide2', 'adhd200', 'allen-brain-observatory', 'centerforopenneuroscience', 'cifar', 'conp-dataset', 'corr', 'crcns', 'dandi', 'datalad', 'dbic', 'devel', 'dicoms', 'hbnssi', 'hcp-openaccess', 'indi', 'kaggle', 'labs', 'naturalistic-data', 'neurovault', 'nidm', 'ohbm', 'openfmri', 'openneuro', 'openneuro-derivatives', 'physionet', 'psychoinformatics-de', 'repronim', 'shub', 'simon', 'studyforrest', 'templateflow', 'workshops'] (protocol_class=GeneratorStdOutErrCapture) (cwd=/home/yoh/proj/datalad/trash/datasets.datalad.org) 
FileNotInRepositoryError:  [Path outside repository: /home/yoh/proj/datalad/trash/datasets.datalad.org]
[Errno None] : Path outside repository: /home/yoh/proj/datalad/trash/datasets.datalad.org: '/tmp/datasets.datalad.org'

```
which shows a completely different codepath/invocation somehow.

**Comment by TheChymera** [comment]
This is what I get with `-l debug`:

```console
[deco]~/.local/share/datalad/mvmnda ❱  datalad -l debug get .
[DEBUG  ] Command line args 1st pass for DataLad 0.19.6. Parsed: Namespace() Unparsed: ['get', '.']
[DEBUG  ] Building doc for <class 'datalad.local.subdatasets.Subdatasets'>
[DEBUG  ] Building doc for <class 'datalad.core.distributed.clone.Clone'>
[DEBUG  ] Building doc for <class 'datalad.distribution.get.Get'>
[DEBUG  ] Parsing known args among ['/usr/lib/python-exec/python3.11/datalad', '-l', 'debug', 'get', '.']
[DEBUG  ] Determined class of decorated function: <class 'datalad.distribution.get.Get'>
[DEBUG  ] Resolved dataset to get content of ['.']: /home/chymera/.local/share/datalad/mvmnda
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin'] (protocol_class=StdOutErrCapture) (cwd=/run/media/chymera/data2/datalad/mvmnda)
[DEBUG  ] Finished ['git', 'config', '-z', '-l', '--show-origin'] with status 0
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin', '--file', '/run/media/chymera/data2/datalad/mvmnda/.datalad/config'] (protocol_class=StdOutErrCapture) (cwd=/run/media/chymera/data2/datalad/mvmnda)
[DEBUG  ] Finished ['git', 'config', '-z', '-l', '--show-origin', '--file', '/run/media/chymera/data2/datalad/mvmnda/.datalad/config'] with status 0
[DEBUG  ] Determined class of decorated function: <class 'datalad.local.subdatasets.Subdatasets'>
[DEBUG  ] Resolved dataset to report on subdataset(s): /home/chymera/.local/share/datalad/mvmnda
[DEBUG  ] Query subdatasets of None
FileNotInRepositoryError:  [Path outside repository: /run/media/chymera/data2/datalad/mvmnda]
[Errno None] : Path outside repository: /run/media/chymera/data2/datalad/mvmnda: '/home/chymera/.local/share/datalad/mvmnda'
```
