### ISSUE TITLE
`test_wtf` fails if `psutil` is installed

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad#7627]
### What is the problem?

Due to a typo in `max_path_length` the following test-errors occur.

On `main`: `test_wtf` fails if `psutil<6.0.0` is installed.
On `master`: `test_wtf` fails if `psutil` is installed. This affects at least version 1.0.0 through 1.1.0

### What steps will reproduce the problem?

Execute `pip install --upgrade datalad` and `pip install --upgrade psutil` in your datalad-venv.

Execute `pytest --pyargs datalad.local.tests.test_wtf` in your datalad-venv

**Comment by mih** [comment]
This is also failing tests in datalad-next. For example: https://ci.appveyor.com/project/mih/datalad-next/builds/50122711/job/l1hyhxx7pbl4etmx

**Comment by yarikoptic** [comment]
https://ci.appveyor.com/project/mih/datalad-next/builds/50122711/job/l1hyhxx7pbl4etmx has code

```
        with swallow_outputs() as cmo:
            wtf(dataset=ds.path, sensitive='all')
            assert_not_in(_HIDDEN, cmo.out)  # all is shown
            assert_in('user.name: ', cmo.out)
            if external_versions['psutil']:
                # filesystems detail should be reported
>               assert_in('max_pathlength:', cmo.out)
../../../venv3.8.17/lib/python3.8/site-packages/datalad/local/tests/test_wtf.py:84: 

```
which is before the https://github.com/datalad/datalad/pull/7622/files fix . As such I consider that this issue was addressed by #7622 merged into `maint` 2 weeks ago.  I now progressed `master` which was at 1.1.0 to 1.1.0-28-gf67e759c6 so should also be fixed in `master`. original post talks about `main` but we do not have any here.

If my analysis is incorrect, feel welcome to reopen.

**Comment by christian-monch** [comment]
I think #7622 does not fix the issue. The issue is a typo in `'max_pathlength:'`, it should be `'max_path_length:'`. This PR fixes the typo. Therefore I reopen the issue.
