### ISSUE TITLE
`create-publication-target-sshwebserver` does not reuse connection

### ISSUE THREAD

**Issue by mih** [datalad/datalad#826]
````
% datalad create-publication-target-sshwebserver localhost:/tmp/dest rmt
2016-09-14 15:43:47,342 [INFO   ] Connecting ... (create_publication_target_sshwebserver.py:209)
mih@localhost's password: 
2016-09-14 15:43:50,244 [INFO   ] Creating target dataset some at /tmp/dest (create_publication_target_sshwebserver.py:239)
2016-09-14 15:43:50,338 [INFO   ] Adjusting remote git configuration (create_publication_target_sshwebserver.py:287)
2016-09-14 15:43:50,357 [INFO   ] Enabling git post-update hook ... (create_publication_target_sshwebserver.py:307)
2016-09-14 15:43:50,430 [INFO   ] Uploading web interface to /tmp/dest (create_publication_target_sshwebserver.py:321)
mih@localhost's password: 
````

password requested twice.

**Comment by yarikoptic** [comment]
may be it was already addressed within #613 ?
```
(git)hopa:/tmp/datasets.datalad.org[master]
$> datalad create-sibling localhost:/tmp/dest rmt
2016-09-20 09:38:58,381 [INFO   ] Connecting ... (create_sibling.py:208)
Enter passphrase for key '/home/yoh/.ssh/id_rsa': 
yoh@localhost's password: 
2016-09-20 09:39:03,732 [INFO   ] Creating target dataset datasets.datalad.org at /tmp/dest (create_sibling.py:238)
2016-09-20 09:39:03,778 [INFO   ] Adjusting remote git configuration (create_sibling.py:286)
2016-09-20 09:39:03,807 [INFO   ] Enabling git post-update hook ... (create_sibling.py:306)
2016-09-20 09:39:03,843 [INFO   ] Uploading web interface to /tmp/dest (create_sibling.py:320)
changes on filesystem:                                                                                                                                  
 openfmri | 0
```

or it could be that there is some `git annex info` call you ran into which didn't reuse it @mih?

**Comment by bpoldrack** [comment]
#613 does not touch anything involving `publish`, `create-publication-target` or relating to SSH somehow.

**Comment by mih** [comment]
This issue is still relevant. I tried to triage it, but failed. When I try a manual simplistic setup it works, but not in the actual combination of datalad's `create_sibling` and the internally called `add_sibling`.

Moreover, I think there is an issue with the control path setup. Will open a dedicated issue.

**Comment by mih** [comment]
So this works:

````
In [5]: ssh = sm.get_connection('localhost:/tmp/dummy')
In [6]: ssh.open()
mih@localhost's password: 
In [7]: ssh.open()
````

but here is how it looks like in `create_sibling`

````
% datalad -l debug create-sibling localhost:/tmp/remote5 sshremote5
2016-10-19 08:33:41,877 [DEBUG  ] Resolved dataset for creating a sibling: <Dataset path=/tmp/origin> 
2016-10-19 08:33:41,927 [INFO   ] Connecting ... 
2016-10-19 08:33:41,928 [DEBUG  ] Reusing known connection for "localhost:/tmp/remote5" 
2016-10-19 08:33:41,928 [DEBUG  ] Try starting control master by calling:
| ['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=yes', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', 'exit'] 
mih@localhost's password: 
<snip>
2016-10-19 08:33:44,728 [DEBUG  ] Adding the siblings 
<snip>
2016-10-19 08:33:44,734 [DEBUG  ] Fetching sibling sshremote5 of origin 
2016-10-19 08:33:44,736 [DEBUG  ] Reusing known connection for "localhost:/tmp/remote5" 
2016-10-19 08:33:44,736 [DEBUG  ] Try starting control master by calling:
| ['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=yes', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', 'exit'] 
2016-10-19 08:33:44,766 [DEBUG  ] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'enableremote', '--debug', 'sshremote5'] 
mih@localhost's password: 
````

**Comment by mih** [comment]
Holy cow:

````
% datalad -l debug create-sibling localhost:/tmp/remote6 sshremote6
2016-10-19 09:41:28,193 [DEBUG  ] Resolved dataset for creating a sibling: <Dataset path=/tmp/origin> 
2016-10-19 09:41:28,258 [INFO   ] Connecting ... 
2016-10-19 09:41:28,259 [DEBUG  ] Reusing known connection for "localhost:/tmp/remote6" 
2016-10-19 09:41:28,259 [DEBUG  ] Try starting control master by calling:
| ['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=yes', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', 'exit'] 
2016-10-19 09:41:28,268 [INFO   ] Creating target dataset origin at /tmp/remote6 
2016-10-19 09:41:28,268 [DEBUG  ] Running: ['ssh', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', "'ls'", "'/tmp/remote6'"] 
2016-10-19 09:41:28,277 [DEBUG  ] Failed to run ['ssh', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', "'ls'", "'/tmp/remote6'"] under None. Exit code=2. out= err=ls: cannot access '/tmp/remote6': No such file or directory
|  
2016-10-19 09:41:28,277 [DEBUG  ] Running: ['ssh', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', "'mkdir'", "'-p'", "'/tmp/remote6'"] 
2016-10-19 09:41:28,288 [DEBUG  ] Running: ['ssh', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', "'git'", "'-C'", "'/tmp/remote6'", "'init'"] 
2016-10-19 09:41:28,300 [DEBUG  ] Running: ['ssh', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', "'git'", "'-C'", "'/tmp/remote6'", "'annex'", "'init'"] 
2016-10-19 09:41:28,367 [INFO   ] Adjusting remote git configuration 
2016-10-19 09:41:28,367 [DEBUG  ] Running: ['ssh', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', "'git'", "'-c'", "'receive.autogc=0'", "'-c'", "'gc.auto=0'", "'version'"] 
2016-10-19 09:41:28,377 [DEBUG  ] Detected git version on server: 2.8.1 
2016-10-19 09:41:28,377 [DEBUG  ] Running: ['ssh', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', "'git'", "'-C'", "'/tmp/remote6'", "'-c'", "'receive.autogc=0'", "'-c'", "'gc.auto=0'", "'config'", "'receive.denyCurrentBranch'", "'updateInstead'"] 
2016-10-19 09:41:28,386 [INFO   ] Enabling git post-update hook ... 
2016-10-19 09:41:28,387 [DEBUG  ] Created temporary thing named /tmp/datalad_temp_PSRDSZ" 
2016-10-19 09:41:28,387 [DEBUG  ] Running: ['scp', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', '/tmp/datalad_temp_PSRDSZ', u'localhost:"/tmp/remote6/.git/hooks/post-update"'] 
2016-10-19 09:41:28,399 [DEBUG  ] Running: ['ssh', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', "'chmod'", "'+x'", "'/tmp/remote6/.git/hooks/post-update'"] 
2016-10-19 09:41:28,409 [DEBUG  ] Running post-update hooks in all created siblings 
2016-10-19 09:41:28,410 [DEBUG  ] Running: ['ssh', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', "cd '/tmp/remote6/.git' && hooks/post-update"] 
2016-10-19 09:41:28,423 [DEBUG  ] Adding the siblings 
2016-10-19 09:41:28,423 [DEBUG  ] Resolved dataset for sibling addition: <Dataset path=/tmp/origin> 
2016-10-19 09:41:28,425 [DEBUG  ] Running: ['git', 'remote', 'add', 'sshremote6', 'localhost:/tmp/remote6'] 
2016-10-19 09:41:28,427 [DEBUG  ] Running: ['git', 'remote', 'set-url', '--push', 'sshremote6', 'localhost:/tmp/remote6'] 
2016-10-19 09:41:28,431 [DEBUG  ] Fetching sibling sshremote6 of origin 
2016-10-19 09:41:28,433 [DEBUG  ] Reusing known connection for "localhost:/tmp/remote6" 
2016-10-19 09:41:28,434 [DEBUG  ] Try starting control master by calling:
| ['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=yes', '-o', u'ControlPath=/home/mih/.config/datalad/localhost', u'localhost', 'exit'] 
2016-10-19 09:41:28,465 [DEBUG  ] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'enableremote', '--debug', 'sshremote6'] 
mih@localhost's password: 
2016-10-19 09:41:31,736 [DEBUG  ] Closing 1 SSH connections... 
2016-10-19 09:41:31,736 [DEBUG  ] Running: ['ssh', '-O', 'stop', '-S', u'/home/mih/.config/datalad/localhost', u'localhost'] 
````

Notice that it only asked for the password at the very end. I Ctrl-C'ed the previous command, which must have left the socket with the open connection behind. It reused it for the initial create action, and again failed to reuse it for `add_sibling`.

1. It should not have been left behind (see #1032 for having complained already)
2. WTF? ;-)

**Comment by bpoldrack** [comment]
Asking twice (or several times in general) seems to be a bug in `SSHConnection.open()`, which tried to create the socket regardless of whether or not it was already there.This doesn't fail, but apparently asks for the password before noticing there's nothing to do. Fixed. PR to come ...

**Comment by bpoldrack** [comment]
Update: There was a second issue in `add_sibling`, which didn't use the repo instance to add a remote and therefore missed the special treatment of ssh remotes. Fixed in #1033 .
